""" add table

Revision ID: fe7f60cdf042
Revises: 18f2614ed619
Create Date: 2020-02-29 17:40:36.227453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7f60cdf042'
down_revision = '18f2614ed619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('t_id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.add_column('user', sa.Column('pwd', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwd')
    op.drop_table('token')
    # ### end Alembic commands ###
